#!/usr/bin/env python3
"""L0 flags-off identity: run every compiled corpus probe on a given engine
checkout and compare engine_trades.csv byte-for-byte against a reference.

IMPORTANT: the committed corpus/validation/<slug>/engine_trades.csv files
can LAG the engine -- they were last regenerated by whatever engine
happened to run scripts/run_corpus.sh at commit time, and may not reflect
legitimate engine work that has landed since. The committed corpus CSVs
are therefore only a DEFAULT/fallback reference (`--reference` unset),
never authoritative on their own for judging "did the new live-runtime
symbols change flags-off behaviour". The authoritative L0 evidence is:
build a checkout of the engine at this branch's OWN fork point (the
merge-base with origin/main, i.e. "flags don't even exist yet"), emit ITS
trades as the reference, then compare this branch's flags-off trades
against THAT -- any remaining diff is unambiguously attributable to work
done on this branch.

Exact three-command procedure for that comparison (run from this repo,
i.e. the branch checkout; BASE is a separate checkout of the engine at the
branch's fork point with the same corpus submodule commit):

    cd $BASE && SKIP_RUN=1 SKIP_VERIFY=1 JOBS=8 scripts/run_corpus.sh
    python3 scripts/live_flags_off_identity.py --root $BASE --emit build/ref_trades_base --jobs 8
    python3 scripts/live_flags_off_identity.py --reference build/ref_trades_base --jobs 8

The first line builds $BASE's corpus strategy libraries (never without
SKIP_RUN=1 -- see below). The second line runs every probe on $BASE's
compiled libraries and captures each one's trades under
build/ref_trades_base/<slug>/engine_trades.csv, plus a provenance.json
recording $BASE's engine/corpus commits and each library's sha256, without
touching $BASE's corpus submodule reference. The third line runs every
probe on THIS checkout's own compiled libraries (default --root) and
compares against those captured trades instead of the (possibly stale)
committed corpus file; it refuses to proceed if the reference's recorded
engine commit and this checkout's engine commit are identical (pass
--allow-same-engine to override that guard deliberately).

Every probe is run to a TEMPORARY output file -- never in place -- so
neither engine root's corpus/validation/<slug>/engine_trades.csv is ever
touched. After the run, `git -C <root>/corpus status --porcelain --
validation` is checked (for the root actually used) and must be empty; a
non-empty result means something wrote into that submodule and the
comparison would have been vacuous.

Prerequisite: build the corpus strategy libraries for the root(s) you are
about to use first (this script does not build):
    SKIP_RUN=1 SKIP_VERIFY=1 JOBS=8 scripts/run_corpus.sh
Never run run_corpus.sh without SKIP_RUN=1 for this purpose -- without it,
step 2 of run_corpus.sh overwrites corpus/validation/<slug>/engine_trades.csv
in place, destroying the very reference this script exists to protect.
"""
from __future__ import annotations

import argparse
import filecmp
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

SCRIPT_ROOT = Path(__file__).resolve().parents[1]


def find_cases(engine_root: Path, only: str | None) -> tuple[list[tuple[Path, str]], list[str]]:
    cases = []
    no_lib = []
    for strat_dir in sorted((engine_root / "corpus/validation").iterdir()):
        if not strat_dir.is_dir():
            continue
        if only and only not in str(strat_dir.relative_to(engine_root)):
            continue
        # Only source-marked strategy directories are runnable (mirrors
        # run_corpus.sh's own filter) -- auxiliary corpus trees intentionally
        # share this layout and are not strategies.
        if not (strat_dir / "strategy.pine").exists() and not (strat_dir / "generated.cpp").exists():
            continue
        so = strat_dir / "strategy.so"
        dylib = strat_dir / "strategy.dylib"
        if so.exists():
            cases.append((strat_dir, "strategy.so"))
        elif dylib.exists():
            cases.append((strat_dir, "strategy.dylib"))
        else:
            no_lib.append(strat_dir.name)
    return cases, no_lib


def run_probe(engine_root: Path, strat_dir: Path, so_name: str, out: Path,
              extra_args: list[str] | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        [
            sys.executable,
            str(engine_root / "scripts/run_strategy.py"),
            str(strat_dir),
            "--so-name",
            so_name,
            "-o",
            str(out),
            *(extra_args or []),
        ],
        capture_output=True,
        text=True,
    )


def last_nonempty_line(text: str) -> str:
    lines = [line for line in text.splitlines() if line.strip()]
    return lines[-1] if lines else "(no output)"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def git_head(repo: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


def engine_head_label(repo: Path) -> str:
    """git_head(repo), with a `-dirty` suffix appended when src/include/
    scripts carry uncommitted changes (final-rereview.md N6): without this,
    a run against just-edited, not-yet-committed sources is indistinguishable
    -- in both the printed comparison line and provenance.json -- from a run
    against the named commit itself, so the evidence alone cannot show which
    sources were actually measured."""
    result = subprocess.run(
        ["git", "-C", str(repo), "status", "--porcelain", "--", "src", "include", "scripts"],
        capture_output=True, text=True, check=True,
    )
    dirty = bool(result.stdout.strip())
    head = git_head(repo)
    return f"{head}-dirty" if dirty else head


def short_engine_label(head_label: str) -> str:
    """Truncate a (possibly `-dirty`-suffixed) engine_head_label to a short,
    printable form without slicing the `-dirty` marker away -- a plain
    `label[:12]` would silently drop it since the full hash is 40 hex
    characters."""
    if head_label.endswith("-dirty"):
        return head_label[: -len("-dirty")][:12] + "-dirty"
    return head_label[:12]


def emit_one(args: tuple[Path, Path, str, Path]) -> tuple[str, bool, str]:
    engine_root, strat_dir, so_name, emit_dir = args
    dest_dir = emit_dir / strat_dir.name
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / "engine_trades.csv"
    with tempfile.TemporaryDirectory() as td:
        out = Path(td) / "engine_trades.csv"
        proc = run_probe(engine_root, strat_dir, so_name, out)
        if proc.returncode != 0:
            return strat_dir.name, False, f"run_strategy.py failed:\n{proc.stdout}\n{proc.stderr}"
        if not out.exists():
            return strat_dir.name, False, "run_strategy.py produced no output"
        shutil.copyfile(out, dest)
        return strat_dir.name, True, ""


def compare_one(args: tuple[Path, Path, str, Path | None]) -> tuple[str, bool, str, str]:
    engine_root, strat_dir, so_name, reference_dir = args
    if reference_dir is not None:
        reference = reference_dir / strat_dir.name / "engine_trades.csv"
        if not reference.exists():
            return strat_dir.name, False, "MISSING", f"reference case missing: {reference}"
    else:
        reference = strat_dir / "engine_trades.csv"
    with tempfile.TemporaryDirectory() as td:
        out = Path(td) / "engine_trades.csv"
        proc = run_probe(engine_root, strat_dir, so_name, out)
        if proc.returncode != 0:
            return strat_dir.name, False, "FAIL", f"run_strategy.py failed:\n{proc.stdout}\n{proc.stderr}"
        if not out.exists():
            return strat_dir.name, False, "FAIL", "run_strategy.py produced no output"
        if not filecmp.cmp(out, reference, shallow=False):
            diff = subprocess.run(["diff", str(out), str(reference)], capture_output=True, text=True)
            return strat_dir.name, False, "DIFF", diff.stdout[:2000]
        return strat_dir.name, True, "", ""


def corpus_clean(engine_root: Path) -> str:
    status = subprocess.run(
        ["git", "-C", str(engine_root / "corpus"), "status", "--porcelain", "--", "validation"],
        capture_output=True,
        text=True,
        check=True,
    )
    return status.stdout


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--jobs", type=int, default=8, help="parallel worker count (default: 8)")
    parser.add_argument("--only", default=None, help="substring filter on the probe path (relative to the engine root)")
    parser.add_argument(
        "--root",
        default=None,
        metavar="DIR",
        help="engine checkout whose scripts/run_strategy.py and "
        "corpus/validation/*/strategy.{so,dylib} are used (default: this "
        "script's own repo)",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--emit",
        default=None,
        metavar="DIR",
        help="write each probe's freshly-run trades to DIR/<slug>/engine_trades.csv "
        "plus DIR/provenance.json, and exit 0 -- no comparison is performed",
    )
    mode.add_argument(
        "--reference",
        default=None,
        metavar="DIR",
        help="compare each probe's freshly-run trades against "
        "DIR/<slug>/engine_trades.csv (and DIR/provenance.json's recorded "
        "engine commit) instead of the committed corpus file; a probe "
        "present in one side and not the other counts as a MISSING failure",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="with --emit, clear a non-empty DIR first instead of refusing to write into it",
    )
    parser.add_argument(
        "--allow-same-engine",
        action="store_true",
        help="with --reference, proceed even when the reference's recorded engine "
        "commit equals the current engine's commit (normally refused: such a "
        "comparison proves nothing)",
    )
    args = parser.parse_args()

    engine_root = Path(args.root).resolve() if args.root else SCRIPT_ROOT
    cases, no_lib = find_cases(engine_root, args.only)
    print(
        f"live_flags_off_identity: {len(no_lib)} source-marked probe dirs had no compiled library"
        + (f": {', '.join(sorted(no_lib))}" if no_lib else "")
    )

    # A run with zero enumerated probes (no libraries compiled, or an
    # --only filter matching nothing) would otherwise fall through every
    # mode below and print "0 probes, 0 differ" / emit nothing / exit 0 --
    # vacuously "passing" while proving nothing. Refuse it in every mode.
    if not cases:
        print(
            "live_flags_off_identity: 0 probes enumerated"
            + (f" (--only={args.only!r} matched nothing)" if args.only else " (no compiled libraries found)")
            + " -- refusing a vacuous run",
            file=sys.stderr,
        )
        return 1

    # --reference mode's whole point is corroborating this run's trades
    # against a known-good reference; a probe that is source-marked but has
    # no compiled library silently narrows that coverage (it is absent from
    # `cases` and never gets a MISSING row from the ref_slugs - run_slugs
    # diff below, since it was never a "run" case at all). Treat it as a
    # hard failure rather than a printed count.
    if args.reference and no_lib:
        print(
            f"live_flags_off_identity: --reference requires every source-marked probe "
            f"to have a compiled library; {len(no_lib)} missing: {', '.join(sorted(no_lib))}",
            file=sys.stderr,
        )
        return 1

    if args.emit:
        emit_dir = Path(args.emit)
        if emit_dir.exists() and any(emit_dir.iterdir()):
            if not args.force:
                print(
                    f"live_flags_off_identity: {emit_dir} is not empty; refusing to emit "
                    "into it (use --force to clear it first)",
                    file=sys.stderr,
                )
                return 1
            if not (emit_dir / "provenance.json").exists():
                print(
                    f"live_flags_off_identity: {emit_dir} is not empty and has no "
                    f"{emit_dir / 'provenance.json'} -- it does not look like a prior "
                    "--emit output, so --force refuses to clear it (rename/remove it "
                    "yourself if that is really what you want)",
                    file=sys.stderr,
                )
                return 1
            shutil.rmtree(emit_dir)
        emit_dir.mkdir(parents=True, exist_ok=True)

        bad: list[str] = []
        details: dict[str, str] = {}
        work = [(engine_root, strat_dir, so_name, emit_dir) for strat_dir, so_name in cases]
        with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
            for name, ok, detail in pool.map(emit_one, work):
                if not ok:
                    bad.append(name)
                    details[name] = detail
        print(f"live_flags_off_identity: emitted {len(cases) - len(bad)}/{len(cases)} probes to {emit_dir}")
        for b in sorted(bad):
            print("  FAILED", b, "-", last_nonempty_line(details[b]))
        if bad:
            for name in sorted(bad)[:3]:
                print(f"--- failure detail (first 2000 chars) for {name} ---")
                print(details[name][:2000])

        provenance = {
            "root": str(engine_root),
            "engine_head": engine_head_label(engine_root),
            "corpus_head": git_head(engine_root / "corpus"),
            "libs": {strat_dir.name: sha256_file(strat_dir / so_name) for strat_dir, so_name in cases},
        }
        (emit_dir / "provenance.json").write_text(json.dumps(provenance, indent=2, sort_keys=True) + "\n")

        status = corpus_clean(engine_root)
        if status.strip():
            print(f"live_flags_off_identity: {engine_root}/corpus/validation was modified by this run:")
            print(status)
            return 1
        return 1 if bad else 0

    reference_dir = Path(args.reference).resolve() if args.reference else None
    reference_engine_head = None

    if not args.reference:
        print(
            "live_flags_off_identity: NOTE: no --reference given -- comparing against "
            "the committed corpus/validation/<slug>/engine_trades.csv, which can lag "
            "the engine. See this script's docstring for the --root/--emit/--reference "
            "three-command procedure against the branch-point engine."
        )

    if reference_dir is not None:
        provenance_path = reference_dir / "provenance.json"
        if not provenance_path.exists():
            print(
                f"live_flags_off_identity: {provenance_path} not found -- this reference "
                "dir was not produced by --emit; refusing to compare without "
                "engine-identity evidence",
                file=sys.stderr,
            )
            return 1
        provenance = json.loads(provenance_path.read_text())
        reference_engine_head = provenance.get("engine_head", "")
        current_engine_head = engine_head_label(engine_root)
        reference_corpus_head = provenance.get("corpus_head", "")
        current_corpus_head = git_head(engine_root / "corpus")
        print(
            f"reference engine {short_engine_label(reference_engine_head)} vs current "
            f"engine {short_engine_label(current_engine_head)} (corpus "
            f"{reference_corpus_head[:12]} vs {current_corpus_head[:12]})"
        )
        if reference_corpus_head != current_corpus_head:
            print(
                f"live_flags_off_identity: reference corpus {reference_corpus_head[:12]} "
                f"!= current corpus {current_corpus_head[:12]} -- the reference was "
                "emitted against a different corpus submodule commit; this comparison "
                "would misattribute corpus drift to engine work (no override)",
                file=sys.stderr,
            )
            return 1
        if reference_engine_head == current_engine_head and not args.allow_same_engine:
            print(
                "live_flags_off_identity: reference engine and current engine are "
                "identical -- this comparison would prove nothing (pass "
                "--allow-same-engine to override deliberately)",
                file=sys.stderr,
            )
            return 1

    bad_tagged: list[tuple[str, str, str]] = []
    work = [(engine_root, strat_dir, so_name, reference_dir) for strat_dir, so_name in cases]
    with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        for name, ok, tag, detail in pool.map(compare_one, work):
            if not ok:
                bad_tagged.append((name, tag, detail))

    if reference_dir is not None:
        run_slugs = {strat_dir.name for strat_dir, _ in cases}
        ref_slugs = {
            p.parent.name
            for p in reference_dir.glob("*/engine_trades.csv")
            if not args.only or args.only in f"corpus/validation/{p.parent.name}"
        }
        for slug in sorted(ref_slugs - run_slugs):
            bad_tagged.append(
                (slug, "MISSING", "present in reference but not produced on this run (no compiled library, or filtered out by --only)")
            )

    diff_count = sum(1 for _, tag, _ in bad_tagged if tag == "DIFF")
    fail_count = sum(1 for _, tag, _ in bad_tagged if tag == "FAIL")
    missing_count = sum(1 for _, tag, _ in bad_tagged if tag == "MISSING")
    ref_suffix = (
        f" (reference engine {short_engine_label(reference_engine_head)})"
        if reference_engine_head else ""
    )

    print(f"live_flags_off_identity: {len(cases)} probes, {diff_count} differ{ref_suffix}")
    print(f"  {diff_count} DIFF, {fail_count} FAIL, {missing_count} MISSING")
    for name, tag, _ in sorted(bad_tagged):
        print(f"  {tag}", name)

    # Proof the reference root's committed corpus was never overwritten in place.
    status = corpus_clean(engine_root)
    if status.strip():
        print(f"live_flags_off_identity: {engine_root}/corpus/validation was modified by this run (reference clobbered):")
        print(status)
        return 1

    if bad_tagged:
        for name, tag, detail in sorted(bad_tagged)[:3]:
            print(f"--- {tag} detail (first 2000 chars) for {name} ---")
            print(detail)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
