#!/usr/bin/env python3
"""L0 flags-off identity: run every compiled corpus probe on a given engine
checkout and compare engine_trades.csv byte-for-byte against a reference.

IMPORTANT: the committed corpus/validation/<slug>/engine_trades.csv files
can LAG the engine -- they were last regenerated by whatever engine
happened to run scripts/run_corpus.sh at commit time (task-10 fix round 1:
the committed reference here was generated by a7cb5b6, 193 commits behind
this branch's own fork point, and does NOT reflect legitimate engine work
that landed since). The committed corpus CSVs are therefore only a
DEFAULT/fallback reference (`--reference` unset), never authoritative on
their own for judging "did the new live-runtime symbols change flags-off
behaviour". The authoritative L0 evidence is: build a checkout of the
engine at this branch's OWN fork point (the merge-base with origin/main,
i.e. "flags don't even exist yet"), emit ITS trades as the reference, then
compare this branch's flags-off trades against THAT -- any remaining diff
is unambiguously attributable to work done on this branch.

Exact three-command procedure for that comparison (run from this repo,
i.e. the branch checkout; BASE is a separate checkout of the engine at the
branch's fork point with the same corpus submodule commit):

    cd $BASE && SKIP_RUN=1 SKIP_VERIFY=1 JOBS=8 scripts/run_corpus.sh
    python3 scripts/live_flags_off_identity.py --root $BASE --emit build/ref_trades_base --jobs 8
    python3 scripts/live_flags_off_identity.py --reference build/ref_trades_base --jobs 8

The first line builds $BASE's corpus strategy libraries (never without
SKIP_RUN=1 -- see the ruling below). The second line runs every probe on
$BASE's compiled libraries and captures each one's trades under
build/ref_trades_base/<slug>/engine_trades.csv, without touching $BASE's
corpus submodule reference. The third line runs every probe on THIS
checkout's own compiled libraries (default --root) and compares against
those captured trades instead of the (possibly stale) committed corpus
file.

Every probe is run to a TEMPORARY output file -- never in place -- so
neither engine root's corpus/validation/<slug>/engine_trades.csv is ever
touched. After the run, `git -C <root>/corpus status --porcelain --
validation` is checked (for the root actually used) and must be empty; a
non-empty result means something wrote into that submodule and the
comparison would have been vacuous.

Prerequisite: build the corpus strategy libraries for the root(s) you are
about to use first (this script does not build):
    SKIP_RUN=1 SKIP_VERIFY=1 JOBS=8 scripts/run_corpus.sh
Never run run_corpus.sh without SKIP_RUN=1 for this purpose -- without it,
step 2 of run_corpus.sh overwrites corpus/validation/<slug>/engine_trades.csv
in place, destroying the very reference this script exists to protect.
"""
from __future__ import annotations

import argparse
import filecmp
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

SCRIPT_ROOT = Path(__file__).resolve().parents[1]


def find_cases(engine_root: Path, only: str | None) -> list[tuple[Path, str]]:
    cases = []
    for strat_dir in sorted((engine_root / "corpus/validation").iterdir()):
        if not strat_dir.is_dir():
            continue
        if only and only not in str(strat_dir):
            continue
        # Only source-marked strategy directories are runnable (mirrors
        # run_corpus.sh's own filter) -- auxiliary corpus trees intentionally
        # share this layout and are not strategies.
        if not (strat_dir / "strategy.pine").exists() and not (strat_dir / "generated.cpp").exists():
            continue
        so = strat_dir / "strategy.so"
        dylib = strat_dir / "strategy.dylib"
        if so.exists():
            cases.append((strat_dir, "strategy.so"))
        elif dylib.exists():
            cases.append((strat_dir, "strategy.dylib"))
        # A probe with neither compiled library is silently skipped -- it
        # did not build (e.g. platform-gated); run_corpus.sh's own build
        # step is the authority on whether that's expected.
    return cases


def run_probe(engine_root: Path, strat_dir: Path, so_name: str, out: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [
            sys.executable,
            str(engine_root / "scripts/run_strategy.py"),
            str(strat_dir),
            "--so-name",
            so_name,
            "-o",
            str(out),
        ],
        capture_output=True,
        text=True,
    )


def emit_one(args: tuple[Path, Path, str, Path]) -> tuple[str, bool, str]:
    engine_root, strat_dir, so_name, emit_dir = args
    dest_dir = emit_dir / strat_dir.name
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / "engine_trades.csv"
    with tempfile.TemporaryDirectory() as td:
        out = Path(td) / "engine_trades.csv"
        proc = run_probe(engine_root, strat_dir, so_name, out)
        if proc.returncode != 0:
            return strat_dir.name, False, f"run_strategy.py failed:\n{proc.stdout}\n{proc.stderr}"
        if not out.exists():
            return strat_dir.name, False, "run_strategy.py produced no output"
        shutil.copyfile(out, dest)
        return strat_dir.name, True, ""


def compare_one(args: tuple[Path, Path, str, Path | None]) -> tuple[str, bool, str]:
    engine_root, strat_dir, so_name, reference_dir = args
    if reference_dir is not None:
        reference = reference_dir / strat_dir.name / "engine_trades.csv"
        if not reference.exists():
            return strat_dir.name, False, f"reference case missing: {reference}"
    else:
        reference = strat_dir / "engine_trades.csv"
    with tempfile.TemporaryDirectory() as td:
        out = Path(td) / "engine_trades.csv"
        proc = run_probe(engine_root, strat_dir, so_name, out)
        if proc.returncode != 0:
            return strat_dir.name, False, f"run_strategy.py failed:\n{proc.stdout}\n{proc.stderr}"
        if not out.exists():
            return strat_dir.name, False, "run_strategy.py produced no output"
        if not filecmp.cmp(out, reference, shallow=False):
            diff = subprocess.run(["diff", str(out), str(reference)], capture_output=True, text=True)
            return strat_dir.name, False, diff.stdout[:2000]
        return strat_dir.name, True, ""


def corpus_clean(engine_root: Path) -> str:
    status = subprocess.run(
        ["git", "-C", str(engine_root / "corpus"), "status", "--porcelain", "--", "validation"],
        capture_output=True,
        text=True,
        check=True,
    )
    return status.stdout


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--jobs", type=int, default=8, help="parallel worker count (default: 8)")
    parser.add_argument("--only", default=None, help="substring filter on the probe path")
    parser.add_argument(
        "--root",
        default=None,
        metavar="DIR",
        help="engine checkout whose scripts/run_strategy.py and "
        "corpus/validation/*/strategy.{so,dylib} are used (default: this "
        "script's own repo)",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--emit",
        default=None,
        metavar="DIR",
        help="write each probe's freshly-run trades to DIR/<slug>/engine_trades.csv "
        "and exit 0 -- no comparison is performed",
    )
    mode.add_argument(
        "--reference",
        default=None,
        metavar="DIR",
        help="compare each probe's freshly-run trades against "
        "DIR/<slug>/engine_trades.csv instead of the committed corpus file; "
        "a probe missing from DIR counts as a DIFF",
    )
    args = parser.parse_args()

    engine_root = Path(args.root).resolve() if args.root else SCRIPT_ROOT
    cases = find_cases(engine_root, args.only)

    if args.emit:
        emit_dir = Path(args.emit)
        emit_dir.mkdir(parents=True, exist_ok=True)
        bad: list[str] = []
        details: dict[str, str] = {}
        work = [(engine_root, strat_dir, so_name, emit_dir) for strat_dir, so_name in cases]
        with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
            for name, ok, detail in pool.map(emit_one, work):
                if not ok:
                    bad.append(name)
                    details[name] = detail
        print(f"live_flags_off_identity: emitted {len(cases) - len(bad)}/{len(cases)} probes to {emit_dir}")
        for b in sorted(bad):
            print("  FAILED", b, "-", details[b].splitlines()[0] if details[b] else "")

        status = corpus_clean(engine_root)
        if status.strip():
            print(f"live_flags_off_identity: {engine_root}/corpus/validation was modified by this run:")
            print(status)
            return 1
        return 1 if bad else 0

    reference_dir = Path(args.reference).resolve() if args.reference else None
    bad = []
    details = {}
    work = [(engine_root, strat_dir, so_name, reference_dir) for strat_dir, so_name in cases]
    with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        for name, ok, detail in pool.map(compare_one, work):
            if not ok:
                bad.append(name)
                details[name] = detail

    print(f"live_flags_off_identity: {len(cases)} probes, {len(bad)} differ")
    for b in sorted(bad):
        print("  DIFF", b)

    # Proof the reference root's committed corpus was never overwritten in place.
    status = corpus_clean(engine_root)
    if status.strip():
        print(f"live_flags_off_identity: {engine_root}/corpus/validation was modified by this run (reference clobbered):")
        print(status)
        return 1

    if bad:
        for name in sorted(bad)[:3]:
            print(f"--- diff (first 2000 chars) for {name} ---")
            print(details[name])
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
