// GENERATED by scripts/gen_pending_order_mirror.py from include/pineforge/engine.hpp -- do not edit.
#include <pineforge/engine.hpp>
#include <pineforge/pending_order_mirror.hpp>

#include <cstddef>
#include <cstring>
#include <type_traits>

static_assert(std::is_standard_layout<pf_pending_order_v1_t>::value,
              "pf_pending_order_v1_t must be standard-layout");
static_assert(std::is_trivial<pf_pending_order_v1_t>::value,
              "pf_pending_order_v1_t must be trivial (memcpy-able across the C ABI)");

namespace pineforge {
namespace {

// NUL-terminated copy of the first STR_CAP-1 bytes + FNV-1a 64 of the
// whole string, so a consumer can still match an over-long id exactly.
void copy_str(const std::string& s, char* dst, uint8_t* truncated, uint64_t* hash) {
    uint64_t h = 1469598103934665603ULL;
    for (unsigned char ch : s) { h ^= ch; h *= 1099511628211ULL; }
    *hash = h;
    const size_t n = s.size() < 63 ? s.size() : 63;
    std::memcpy(dst, s.data(), n);
    dst[n] = 0;
    *truncated = s.size() > 63 ? 1 : 0;
}

}  // namespace

void fill_pending_order_mirror(const PendingOrder& src, pf_pending_order_v1_t* out) {
    std::memset(out, 0, sizeof(*out));
    out->struct_version = 1;
    out->size = (uint32_t)sizeof(*out);
    copy_str(src.id, out->id, &out->id_truncated, &out->id_hash64);
    copy_str(src.from_entry, out->from_entry, &out->from_entry_truncated, &out->from_entry_hash64);
    out->type = (int32_t)src.type;
    out->is_long = src.is_long ? 1 : 0;
    out->limit_price = src.limit_price;
    out->stop_price = src.stop_price;
    out->trail_points = src.trail_points;
    out->trail_price = src.trail_price;
    out->trail_offset = src.trail_offset;
    out->profit_ticks = src.profit_ticks;
    out->loss_ticks = src.loss_ticks;
    out->qty = src.qty;
    out->qty_type = (int32_t)src.qty_type;
    out->qty_percent = src.qty_percent;
    copy_str(src.oca_name, out->oca_name, &out->oca_name_truncated, &out->oca_name_hash64);
    out->oca_type = (int32_t)src.oca_type;
    out->created_bar = (int32_t)src.created_bar;
    out->created_seq = src.created_seq;
    out->incarnation = src.incarnation;
    out->created_by_same_id_replacement = src.created_by_same_id_replacement ? 1 : 0;
    out->replaced_default_market_incarnation = src.replaced_default_market_incarnation;
    out->declined_by_replaced_short_market = src.declined_by_replaced_short_market ? 1 : 0;
    out->replaced_exit_order_incarnation = src.replaced_exit_order_incarnation;
    out->recreated_after_named_cancelled_entry_incarnation = src.recreated_after_named_cancelled_entry_incarnation;
    out->named_cancel_surviving_exit_incarnation = src.named_cancel_surviving_exit_incarnation;
    out->stop_limit_activated = src.stop_limit_activated ? 1 : 0;
    out->coof_suppress_stop_on_entry_bar = src.coof_suppress_stop_on_entry_bar ? 1 : 0;
    out->coof_suppress_limit_on_entry_bar = src.coof_suppress_limit_on_entry_bar ? 1 : 0;
    out->created_during_coof_recalc = src.created_during_coof_recalc ? 1 : 0;
    out->coof_born_at_close_recalc = src.coof_born_at_close_recalc ? 1 : 0;
    out->coof_born_mid_bar = src.coof_born_mid_bar ? 1 : 0;
    out->coof_cascade_seg_i = (int32_t)src.coof_cascade_seg_i;
    out->coof_cascade_inflight_fires = src.coof_cascade_inflight_fires ? 1 : 0;
    out->created_position_side = (int32_t)src.created_position_side;
    out->created_position_cycle_seq = src.created_position_cycle_seq;
    out->created_after_position_close_in_bar = src.created_after_position_close_in_bar ? 1 : 0;
    out->over_pyramiding_cap_at_placement = src.over_pyramiding_cap_at_placement ? 1 : 0;
    out->same_id_stop_deferred_close_all_bar = (int32_t)src.same_id_stop_deferred_close_all_bar;
    out->same_id_stop_deferred_close_all_incarnation = src.same_id_stop_deferred_close_all_incarnation;
    out->reverses_same_bar_market_from_flat = src.reverses_same_bar_market_from_flat ? 1 : 0;
    out->paired_flat_market_candidate = src.paired_flat_market_candidate ? 1 : 0;
    out->paired_flat_market_own_qty = src.paired_flat_market_own_qty;
    out->paired_flat_market_signal_close = src.paired_flat_market_signal_close;
    out->paired_flat_market_signal_equity = src.paired_flat_market_signal_equity;
    out->paired_flat_market_signal_margin_pct = src.paired_flat_market_signal_margin_pct;
    out->paired_flat_market_signal_pointvalue = src.paired_flat_market_signal_pointvalue;
    out->paired_flat_market_signal_fx = src.paired_flat_market_signal_fx;
    out->paired_flat_market_peer_seq = src.paired_flat_market_peer_seq;
    out->paired_flat_market_transaction_qty = src.paired_flat_market_transaction_qty;
    out->default_flat_market_gross_candidate = src.default_flat_market_gross_candidate ? 1 : 0;
    out->tv_carry_qty = src.tv_carry_qty;
    out->frozen_default_qty = src.frozen_default_qty;
    out->default_stop_placement_qty = src.default_stop_placement_qty;
    out->default_stop_placement_equity = src.default_stop_placement_equity;
    out->default_stop_placement_signal_close = src.default_stop_placement_signal_close;
    out->default_stop_sizing_price = src.default_stop_sizing_price;
    out->sizing_equity = src.sizing_equity;
    out->sizing_price = src.sizing_price;
    out->sizing_fx = src.sizing_fx;
    out->sizing_mark = src.sizing_mark;
    out->opening_affordability_exemption_candidate = src.opening_affordability_exemption_candidate ? 1 : 0;
    out->explicit_flat_admission_candidate = src.explicit_flat_admission_candidate ? 1 : 0;
    out->explicit_placement_equity = src.explicit_placement_equity;
    out->explicit_slipped_signal_close = src.explicit_slipped_signal_close;
    out->affordability_placement_equity = src.affordability_placement_equity;
    out->affordability_signal_price = src.affordability_signal_price;
    out->affordability_held_qty = src.affordability_held_qty;
    out->affordability_close_only = src.affordability_close_only ? 1 : 0;
    out->rounded_signal_cost_close_only = src.rounded_signal_cost_close_only ? 1 : 0;
    out->signal_close_mc_bar = (int32_t)src.signal_close_mc_bar;
    out->signal_close_mc_entry_incarnation = src.signal_close_mc_entry_incarnation;
    out->signal_close_mc_fill_seq = src.signal_close_mc_fill_seq;
    out->signal_close_mc_remaining_qty = src.signal_close_mc_remaining_qty;
    copy_str(src.comment, out->comment, &out->comment_truncated, &out->comment_hash64);
    out->requested_partial = src.requested_partial ? 1 : 0;
    out->full_percent_exit_request = src.full_percent_exit_request ? 1 : 0;
    out->pooc_global_full_exit_dynamic_qty = src.pooc_global_full_exit_dynamic_qty ? 1 : 0;
    out->pooc_global_full_exit_tracks_bound_adds = src.pooc_global_full_exit_tracks_bound_adds ? 1 : 0;
    out->pooc_global_full_exit_bound_add = src.pooc_global_full_exit_bound_add ? 1 : 0;
    out->created_while_in_position = src.created_while_in_position ? 1 : 0;
    out->sbmt_member = src.sbmt_member ? 1 : 0;
    out->sbmt_own_qty = src.sbmt_own_qty;
    out->sbmt_tx_qty = src.sbmt_tx_qty;
    out->sbmt_kept_over_cap = src.sbmt_kept_over_cap ? 1 : 0;
    out->sbmt_close_qty = src.sbmt_close_qty;
    out->sbmt_close_buy = src.sbmt_close_buy ? 1 : 0;
    out->suppress_as_declined_reversal_close = src.suppress_as_declined_reversal_close ? 1 : 0;
    out->dormant_bracket = src.dormant_bracket ? 1 : 0;
    out->dormant_reissue_pending = src.dormant_reissue_pending ? 1 : 0;
    out->dormant_original_stop_price = src.dormant_original_stop_price;
    out->dormant_hold_bar = (int32_t)src.dormant_hold_bar;
    out->dormant_reversal_kill_bar = (int32_t)src.dormant_reversal_kill_bar;
    out->dormant_trail_best = src.dormant_trail_best;
    out->dormant_trail_best_start = src.dormant_trail_best_start;
    out->dormant_trail_leg_dead = src.dormant_trail_leg_dead ? 1 : 0;
    out->suppressed_close_consumed_ledger_qty = src.suppressed_close_consumed_ledger_qty;
    out->suppressed_close_retired_ledger_qty = src.suppressed_close_retired_ledger_qty;
    out->short_seed_collision_role = (int32_t)src.short_seed_collision_role;
}

namespace {

#define PF_PO_FIELD(name, type) \
    { #name, type, (uint32_t)offsetof(pf_pending_order_v1_t, name), \
      (uint32_t)sizeof(((pf_pending_order_v1_t*)0)->name) }

const pf_field_desc_t kLayout[] = {
    PF_PO_FIELD(struct_version, "uint32_t"),
    PF_PO_FIELD(size, "uint32_t"),
    PF_PO_FIELD(id, "char[64]"),
    PF_PO_FIELD(id_truncated, "uint8_t"),
    PF_PO_FIELD(id_hash64, "uint64_t"),
    PF_PO_FIELD(from_entry, "char[64]"),
    PF_PO_FIELD(from_entry_truncated, "uint8_t"),
    PF_PO_FIELD(from_entry_hash64, "uint64_t"),
    PF_PO_FIELD(type, "int32_t"),
    PF_PO_FIELD(is_long, "uint8_t"),
    PF_PO_FIELD(limit_price, "double"),
    PF_PO_FIELD(stop_price, "double"),
    PF_PO_FIELD(trail_points, "double"),
    PF_PO_FIELD(trail_price, "double"),
    PF_PO_FIELD(trail_offset, "double"),
    PF_PO_FIELD(profit_ticks, "double"),
    PF_PO_FIELD(loss_ticks, "double"),
    PF_PO_FIELD(qty, "double"),
    PF_PO_FIELD(qty_type, "int32_t"),
    PF_PO_FIELD(qty_percent, "double"),
    PF_PO_FIELD(oca_name, "char[64]"),
    PF_PO_FIELD(oca_name_truncated, "uint8_t"),
    PF_PO_FIELD(oca_name_hash64, "uint64_t"),
    PF_PO_FIELD(oca_type, "int32_t"),
    PF_PO_FIELD(created_bar, "int32_t"),
    PF_PO_FIELD(created_seq, "int64_t"),
    PF_PO_FIELD(incarnation, "uint64_t"),
    PF_PO_FIELD(created_by_same_id_replacement, "uint8_t"),
    PF_PO_FIELD(replaced_default_market_incarnation, "uint64_t"),
    PF_PO_FIELD(declined_by_replaced_short_market, "uint8_t"),
    PF_PO_FIELD(replaced_exit_order_incarnation, "uint64_t"),
    PF_PO_FIELD(recreated_after_named_cancelled_entry_incarnation, "uint64_t"),
    PF_PO_FIELD(named_cancel_surviving_exit_incarnation, "uint64_t"),
    PF_PO_FIELD(stop_limit_activated, "uint8_t"),
    PF_PO_FIELD(coof_suppress_stop_on_entry_bar, "uint8_t"),
    PF_PO_FIELD(coof_suppress_limit_on_entry_bar, "uint8_t"),
    PF_PO_FIELD(created_during_coof_recalc, "uint8_t"),
    PF_PO_FIELD(coof_born_at_close_recalc, "uint8_t"),
    PF_PO_FIELD(coof_born_mid_bar, "uint8_t"),
    PF_PO_FIELD(coof_cascade_seg_i, "int32_t"),
    PF_PO_FIELD(coof_cascade_inflight_fires, "uint8_t"),
    PF_PO_FIELD(created_position_side, "int32_t"),
    PF_PO_FIELD(created_position_cycle_seq, "int64_t"),
    PF_PO_FIELD(created_after_position_close_in_bar, "uint8_t"),
    PF_PO_FIELD(over_pyramiding_cap_at_placement, "uint8_t"),
    PF_PO_FIELD(same_id_stop_deferred_close_all_bar, "int32_t"),
    PF_PO_FIELD(same_id_stop_deferred_close_all_incarnation, "uint64_t"),
    PF_PO_FIELD(reverses_same_bar_market_from_flat, "uint8_t"),
    PF_PO_FIELD(paired_flat_market_candidate, "uint8_t"),
    PF_PO_FIELD(paired_flat_market_own_qty, "double"),
    PF_PO_FIELD(paired_flat_market_signal_close, "double"),
    PF_PO_FIELD(paired_flat_market_signal_equity, "double"),
    PF_PO_FIELD(paired_flat_market_signal_margin_pct, "double"),
    PF_PO_FIELD(paired_flat_market_signal_pointvalue, "double"),
    PF_PO_FIELD(paired_flat_market_signal_fx, "double"),
    PF_PO_FIELD(paired_flat_market_peer_seq, "int64_t"),
    PF_PO_FIELD(paired_flat_market_transaction_qty, "double"),
    PF_PO_FIELD(default_flat_market_gross_candidate, "uint8_t"),
    PF_PO_FIELD(tv_carry_qty, "double"),
    PF_PO_FIELD(frozen_default_qty, "double"),
    PF_PO_FIELD(default_stop_placement_qty, "double"),
    PF_PO_FIELD(default_stop_placement_equity, "double"),
    PF_PO_FIELD(default_stop_placement_signal_close, "double"),
    PF_PO_FIELD(default_stop_sizing_price, "double"),
    PF_PO_FIELD(sizing_equity, "double"),
    PF_PO_FIELD(sizing_price, "double"),
    PF_PO_FIELD(sizing_fx, "double"),
    PF_PO_FIELD(sizing_mark, "double"),
    PF_PO_FIELD(opening_affordability_exemption_candidate, "uint8_t"),
    PF_PO_FIELD(explicit_flat_admission_candidate, "uint8_t"),
    PF_PO_FIELD(explicit_placement_equity, "double"),
    PF_PO_FIELD(explicit_slipped_signal_close, "double"),
    PF_PO_FIELD(affordability_placement_equity, "double"),
    PF_PO_FIELD(affordability_signal_price, "double"),
    PF_PO_FIELD(affordability_held_qty, "double"),
    PF_PO_FIELD(affordability_close_only, "uint8_t"),
    PF_PO_FIELD(rounded_signal_cost_close_only, "uint8_t"),
    PF_PO_FIELD(signal_close_mc_bar, "int32_t"),
    PF_PO_FIELD(signal_close_mc_entry_incarnation, "uint64_t"),
    PF_PO_FIELD(signal_close_mc_fill_seq, "uint64_t"),
    PF_PO_FIELD(signal_close_mc_remaining_qty, "double"),
    PF_PO_FIELD(comment, "char[64]"),
    PF_PO_FIELD(comment_truncated, "uint8_t"),
    PF_PO_FIELD(comment_hash64, "uint64_t"),
    PF_PO_FIELD(requested_partial, "uint8_t"),
    PF_PO_FIELD(full_percent_exit_request, "uint8_t"),
    PF_PO_FIELD(pooc_global_full_exit_dynamic_qty, "uint8_t"),
    PF_PO_FIELD(pooc_global_full_exit_tracks_bound_adds, "uint8_t"),
    PF_PO_FIELD(pooc_global_full_exit_bound_add, "uint8_t"),
    PF_PO_FIELD(created_while_in_position, "uint8_t"),
    PF_PO_FIELD(sbmt_member, "uint8_t"),
    PF_PO_FIELD(sbmt_own_qty, "double"),
    PF_PO_FIELD(sbmt_tx_qty, "double"),
    PF_PO_FIELD(sbmt_kept_over_cap, "uint8_t"),
    PF_PO_FIELD(sbmt_close_qty, "double"),
    PF_PO_FIELD(sbmt_close_buy, "uint8_t"),
    PF_PO_FIELD(suppress_as_declined_reversal_close, "uint8_t"),
    PF_PO_FIELD(dormant_bracket, "uint8_t"),
    PF_PO_FIELD(dormant_reissue_pending, "uint8_t"),
    PF_PO_FIELD(dormant_original_stop_price, "double"),
    PF_PO_FIELD(dormant_hold_bar, "int32_t"),
    PF_PO_FIELD(dormant_reversal_kill_bar, "int32_t"),
    PF_PO_FIELD(dormant_trail_best, "double"),
    PF_PO_FIELD(dormant_trail_best_start, "double"),
    PF_PO_FIELD(dormant_trail_leg_dead, "uint8_t"),
    PF_PO_FIELD(suppressed_close_consumed_ledger_qty, "double"),
    PF_PO_FIELD(suppressed_close_retired_ledger_qty, "double"),
    PF_PO_FIELD(short_seed_collision_role, "int32_t"),
};

#undef PF_PO_FIELD

}  // namespace

const pf_field_desc_t* pending_order_layout(int* count) {
    if (count) *count = (int)(sizeof(kLayout) / sizeof(kLayout[0]));
    return kLayout;
}

}  // namespace pineforge
